# Config file for [Air](https://github.com/cosmtrek/air) in TOML format

# Working directory
# . or absolute path, please note that the directories following must be under root
root = "." 
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
  # Just plain old shell command. You could use `make` as well.
  cmd = "go build -o ./tmp/app/main ./app/main.go"
  # Binary file yields from `cmd`.
  bin = "tmp/app"

  # Customize binary.
  # This is how you start to run your application. Since my application will works like CLI, so to run it, like to make a CLI call.
  full_bin = "./tmp/app/main"

  include_dir = []
  # Watch these filename extensions.
  include_ext = ["go", "tpl", "yaml", "tmpl", "html"]

  # Ignore these filename extensions or directories.
  exclude_dir = ["assets", "tmp", "vendor", "testdata", "mysql", "scripts", "docs", "diagrams"]
  exclude_file = ["docker-compose.yaml", "Dockerfile"]
  exclude_regex = ["_test.go"]


  # This log file places in your tmp_dir.
  log = "air_errors.log"

  send_interrupt = false
  stop_on_error = true

  # It's not necessary to trigger build each time file changes if it's too frequent.
  delay = 1000 # ms

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  # Show log time
  time = true

[misc]
  # Delete tmp directory on exit
  clean_on_exit = true
